routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EmployeeDependantController;
use App\Http\Controllers\ContactPersonController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require __DIR__.'/auth.php';

Route::middleware(['auth'])->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/test', [UserController::class, 'test'])->name('test');
    
    Route::resource('/dependants', EmployeeDependantController::class);
    Route::resource('/contactPerson', ContactPersonController::class);
    
    
    Route::resource('/employees', EmployeeController::class);
    Route::group(['prefix' => 'employees','as' => 'employees.'],function(){
        Route::post('/{id}/contact-person', [EmployeeController::class, 'storeContactPerson'])->name('store.contactPerson');
        Route::post('/{id}/dependants', [EmployeeController::class, 'storeDependants'])->name('store.dependants');
        Route::post('/{id}/education', [EmployeeController::class, 'storeEducation'])->name('store.educationDetail');
        Route::post('/{id}/bank-details', [EmployeeController::class, 'storeAccountDetails'])->name('store.accountDetails');
        Route::post('/{id}/documents', [EmployeeController::class, 'storeDocuments'])->name('store.documents');
        Route::post('/{id}/assets', [EmployeeController::class, 'storeAssets'])->name('store.assets');
        Route::post('/{id}/dependant-benefits', [EmployeeController::class, 'storeDependantBenefits'])->name('store.dependantBenefits');
        Route::put('/{id}/main-info', [EmployeeController::class, 'updateEmployeeMainInfo'])->name('update.mainInfo');
        Route::put('/{id}/personal-details', [EmployeeController::class, 'updateEmployeePersonalDetails'])->name('update.personalDetails');
        Route::put('/{id}/employee-contact', [EmployeeController::class, 'updateEmployeeContactDetails'])->name('update.contactDetails');
        Route::put('/{id}/employee-official-details', [EmployeeController::class, 'updateEmployeeOfficialDetails'])->name('update.officialDetails');
        Route::put('/{id}/employee-profile-image', [EmployeeController::class, 'updateProfileImage'])->name('update.profileImage');
        Route::put('/{id}/employee-rules', [EmployeeController::class, 'updateEmployeeRules'])->name('update.employeeRules');
    });
});

app/Models/EmployeeType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class EmployeeType extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'name',
        'description',
        'status',
        'created_by',
        'updated_by',
    ];

    public function employees(){
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\EmployeeType;
use App\Models\VisaStatus;
use App\Models\EmployeeCategory;
use App\Models\Company;
use App\Models\Sponsor;
use App\Models\PayGroup;
use App\Models\Country;
use App\Models\City;
use App\Models\Relation;
use App\Models\Religion;
use App\Models\EmployeeDependant;
use App\Models\Qualification;
use App\Models\Institute;
use App\Models\Bank;
use App\Models\DocumentType;
use App\Models\DocumentStatus;
use App\Models\AssetType;
use App\Models\AssetCondition;
use App\Models\AssetBrand;
use App\Models\Currency;
use App\Models\InsuranceCategory;
use App\Models\InsuranceCompany;
use App\Models\Route;
use App\Models\PositionCategory;
use App\Models\Designation;
use App\Models\Department;
use App\Models\SubDepartment;
use App\Models\CostCenter;
use App\Models\Project;
use App\Models\TicketEntitlement;
use App\Models\EmployeeStatus;
use App\Models\ContractType;
use App\Models\Shift;
use App\Models\LeavePerAnnum;
use App\Http\Requests\EditUserProfile;
use Illuminate\Http\Request;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image as Image;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = User::get()->all();
        return view('employees.list', ['employees' => $employees]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $employee = User::create([
            'employee_id' => 'EMP_ID_004',
            'personal_id' => $request->personal_id,
            'emirates_id' => $request->emirates_id,
            'first_name' => $request->first_name,
            'middle_name' => $request->middle_name,
            'last_name' => $request->last_name,
            'full_name' => $request->first_name . ' ' . $request->middle_name . ' ' . $request->last_name,
            'email' => $request->email,
            'password' => Hash::make('password'),
            'home_phone_number' => $request->home_phone_number,
            'profile_image' => 'default_image.jpg',
        ]);
        return redirect()->route('employees.index')->with('status', 'Employee Created Successfuly!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(user $employee)
    {
        // return [$employee->dependants];
        $employee = User::with([
            'employeeType',
            'visaStatus',
            'employeeCategory',
            'contactPeoples.relationName',
            'linemanager',
            'dependants.relation',
            'educations.country',
            'educations.qualification',
            'employeeBankDetail'
        ])->find($employee->employee_id);
        $contactPersons = $employee->contactPeoples;
        $educations = $employee->educations;
        $employeeDependants = $employee->dependants;
        $employeeEducations = $employee->education;
        $employeeDocuments = $employee->documents;
        $employeeDependantsBenefits = $employee->dependantBenefits;
        $employeeAssets = $employee->assets;
        $bankDetails = $employee->bankDetails;
        $employee_types = EmployeeType::select(['id', 'name'])->get();
        $employee_categories = EmployeeCategory::select(['id', 'name'])->get();
        $visa_statuses = VisaStatus::select(['id', 'name'])->get();
        $line_managers = User::select(['employee_id', 'full_name'])->get();
        $companies = Company::select(['id', 'name'])->get();
        $sponsors = Sponsor::select(['id', 'name'])->get();
        $pay_groups = PayGroup::select(['id', 'name'])->get();
        $nationalities = Country::select(['id', 'name'])->get();
        $relations = Relation::select(['id', 'name'])->get();
        $religions = Religion::select(['id', 'name'])->get();
        $document_statuses = DocumentStatus::select(['id', 'name'])->get();
        $document_types = DocumentType::select(['id', 'name'])->get();
        $asset_types = AssetType::select(['id', 'name'])->get();
        $asset_conditions = AssetCondition::select(['id', 'name'])->get();
        $asset_brands = AssetBrand::select(['id', 'name'])->get();
        $banks = Bank::select(['id', 'name'])->get();
        $qualifications = Qualification::select(['id', 'name'])->get();
        $institutes = Institute::select(['id', 'name'])->get();
        $currencies = Currency::select(['id', 'name', 'symbol'])->get();
        $employee_dependent_names = EmployeeDependant::select(['id', 'name'])->where('user_employee_id', $employee->employee_id)->get();
        $insurance_companies = InsuranceCompany::select(['id', 'name'])->get();
        $insurance_categories = InsuranceCategory::select(['id', 'name'])->get();
        $ticket_entitlements = TicketEntitlement::select(['id', 'name'])->get();
        $routes = Route::select(['id', 'name'])->get();
        $positionCategories = PositionCategory::select(['id', 'name'])->get();
        $designations = Designation::select(['id', 'name'])->get();
        $departments = Department::select(['id', 'name'])->get();
        $subDepartments = SubDepartment::select(['id', 'name'])->get();
        $cities = City::select(['id', 'name', 'country_id'])->get();
        $costCenters = CostCenter::select(['id', 'name'])->get();
        $projects = Project::select(['id', 'name'])->get();
        $employeeStatuses = EmployeeStatus::select(['id', 'name'])->get();
        $contractTypes = ContractType::select(['id', 'name'])->get();
        $shifts = Shift::select(['id', 'name'])->get();
        $leaveRules = LeavePerAnnum::select(['id', 'name'])->get();
        $maritialStatus = config('basic.maritial_status');
        $bloodGroup = config('basic.blood_group');
        $employeeGender = config('basic.employee_gender');
        $probationPeriod = config('basic.probation_period');

        return view('employees.profile', [
            'contractTypes'             => $contractTypes,
            'shifts'                    => $shifts,
            'leaveRules'                => $leaveRules,
            'countries'                 => $nationalities,
            'employee'                  => $employee,
            'employee_types'            => $employee_types,
            'visa_statuses'             => $visa_statuses,
            'employee_categories'       => $employee_categories,
            'line_managers'             => $line_managers,
            'companies'                 => $companies,
            'sponsors'                  => $sponsors,
            'pay_groups'                => $pay_groups,
            'nationalities'             => $nationalities,
            'relations'                 => $relations,
            'religions'                 => $religions,
            'employeeDependants'        => $employeeDependants,
            'qualifications'            => $qualifications,
            'institutes'                => $institutes,
            'contactPersons'            => $contactPersons,
            'educations'                => $educations,
            'bankDetails'               => $bankDetails,
            'banks'                     => $banks,
            'document_statuses'         => $document_statuses,
            'document_types'            => $document_types,
            'employeeDocuments'         => $employeeDocuments,
            'asset_types'               => $asset_types,
            'asset_conditions'          => $asset_conditions,
            'asset_brands'              => $asset_brands,
            'currencies'                => $currencies,
            'employeeAssets'            => $employeeAssets,
            'employee_dependent_names'  => $employee_dependent_names,
            'insurance_companies'       => $insurance_companies,
            'insurance_categories'      => $insurance_categories,
            'ticket_entitlements'       => $ticket_entitlements,
            'routes'                    => $routes,
            'employeeDependantsBenefits' => $employeeDependantsBenefits,
            'maritialStatus'            => $maritialStatus,
            'bloodGroup'                => $bloodGroup,
            'employeeGender'            => $employeeGender,
            'probationPeriod'           => $probationPeriod,
            'positionCategories'        => $positionCategories,
            'designations'              => $designations,
            'departments'               => $departments,
            'subDepartments'            => $subDepartments,
            'cities'                    => $cities,
            'costCenters'               => $costCenters,
            'projects'                  => $projects,
            'employeeStatuses'          => $employeeStatuses
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(user $employee)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EditUserProfile $request, user $employee)
    {
        try {
            $full_name = $request->first_name . ' ' . $request->middle_name . ' ' . $request->last_name;

resources/views/employees/modals/dependant-benefits.blade.php
<form action="{{ route('employees.store.dependantBenefits', [$employee->employee_id]) }}" method="POST">
    @csrf
    <div class="modal fade" id="dependant-benefits" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="title" id="defaultModalLabel">Dependant Benefits</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group col-6 pull-left">
                        <label for="employee_dependant_id">Dependant Full Name</label>
                        <select name="employee_dependant_id" class="simple-select2 w-100">
                            <option value="">Dependant Full Name</option>
                            @foreach($employee_dependent_names as $employee_dependent_names)
                            <option value="{{ $employee_dependent_names->id }}">{{ $employee_dependent_names->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-6 pull-left">
                        <label for="ticket_entitlement_id">Ticket Entitlement</label>
                        <select name="ticket_entitlement_id" class="simple-select2 w-100">
                            <option value="">Ticket</option>
                            @foreach($ticket_entitlements as $ticket_entitlement)
                            <option value="{{ $ticket_entitlement->id }}">{{ $ticket_entitlement->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-7 pull-left">
                        <label for="routes_from_id">Route From</label>
                        <select name="routes_from_id" id="routes_from_id" class="simple-select2 w-100">
                            <option value="">Route From</option>
                            @foreach($routes as $route)
                            <option value="{{ $route->id }}">{{ $route->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-5 pull-left">
                        <label for="start">Date</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="icon-calendar"></i></span>
                            </div>
                            <input name="start" data-provide="datepicker" data-date-autoclose="true" class="form-control" data-date-format="yyyy-mm-dd" placeholder="Date">
                        </div>
                    </div>
                    <div class="form-group col-7 pull-left">
                        <label for="routes_to_id">Route To</label>
                        <select name="routes_to_id" id="routes_to_id" class="simple-select2 w-100">
                            <option value="">Route To</option>
                            @foreach($routes as $route)
                            <option value="{{ $route->id }}">{{ $route->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-5 pull-left">
                        <label for="end">Date</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="icon-calendar"></i></span>
                            </div>
                            <input name="end" data-provide="datepicker" data-date-autoclose="true" class="form-control" data-date-format="yyyy-mm-dd" placeholder="Date">
                        </div>
                    </div>
                    <div class="form-group col-6 pull-left">
                        <label for="insurance_company_id">Insurance Company</label>
                        <select name="insurance_company_id" class="simple-select2 w-100">
                            <option value="">Insurance Company</option>
                            @foreach($insurance_companies as $insurance_companie)
                            <option value="{{ $insurance_companie->id }}">{{ $insurance_companie->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-6 pull-left">
                        <label for="insurance_category_id">Insurance Category</label>
                        <select name="insurance_category_id" class="simple-select2 w-100">
                            <option value="">Insurance Category</option>
                            @foreach($insurance_categories as $insurance_categorie)
                            <option value="{{ $insurance_categorie->id }}">{{ $insurance_categorie->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-6 pull-left">
                        <label for="policy_number">Policy Number</label>
                        <input type="text" class="form-control" name="policy_number" id="policy_number" placeholder="Policy Number">
                    </div>
                    <div class="form-group col-6 pull-left">
                        <label for="currency_id">Currency</label>
                        <select name="currency_id" id="currency_id" class="simple-select2 w-100">
                            <option value="">Currency</option>
                            @foreach($currencies as $currency)
                            <option value="{{ $currency->id }}">{{ $currency->symbol }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-6 pull-left">
                        <label for="fare_amount">Fare Amount</label>
                        <input type="text" class="form-control" name="fare_amount" id="fare_amount" placeholder="Fare Amount" value="">
                    </div>
                    <div class="form-group col-6 pull-left">
                        <label for="premium">Premium</label>
                        <input type="text" class="form-control" name="premium" id="premium" placeholder="Premium">
                    </div>
                    <div class="form-group col-6 pull-left">
                        <label for="insurance_amount">Insurance Amount</label>
                        <input type="text" class="form-control" name="insurance_amount" id="insurance_amount" placeholder="Insurance Amount">
                    </div>
                    <div class="form-group col-md-12 pull-left">
                        <label for="description">Description</label>
                        <textarea name="description" id="description" class="form-control"></textarea>
                    </div>
			    </div>
                <div class="modal-footer" id="modal-footer">
                    <div id="dependant_div">
                        <button type="submit" class="btn btn-primary">SAVE CHANGES</button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">CLOSE</button>
                    </div>
                </div>
		    </div>
        </div>
    </div>
</form>

resources/views/employees/modals/emergency-contacts.blade.php
<form action="{{ route('employees.store.contactPerson', [$employee->employee_id]) }}" method="POST">
    @csrf
    <div class="modal fade" id="emergency-contacts" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="title" id="defaultModalLabel">Emergency Contact Details</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group col-6 pull-left">
                        <label for="full_name">Full Name</label>
                        <input type="text" class="form-control" name="full_name" id="full_name" placeholder="Full Name" value="">
                    </div>
                    <div class="form-group col-6 pull-left">
                        <label for="email">Email</label>
                        <input type="text" class="form-control" name="email" id="email" placeholder="Email">
                    </div>
                    <div class="form-group col-12 pull-left">
						<label for="relation">Relation</label>
						<select name="relation" class="simple-select2 w-100">
							<option value="">Relation</option>
                            @foreach($relations as $relation)
                                <option value="{{ $relation->id }}">{{ $relation->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-4 pull-left">
                        <label for="mobile_number">Mobile Number</label>
                        <input type="text" class="form-control" name="mobile_number" id="mobile_number" placeholder="Mobile Number">
                    </div>
                    <div class="form-group col-4 pull-left">
                        <label for="home_phone_number">Home Number</label>
                        <input type="text" class="form-control" name="home_phone_number" id="home_phone_number" placeholder="Home Number">
                    </div>
                    <div class="form-group col-4 pull-left">
                        <label for="work_number">Work Number</label>
                        <input type="text" class="form-control" name="work_number" id="work_number" placeholder="Work Number">
                    </div>
                    <div class="form-group col-12 pull-left">
                        <label for="address">Address</label>
                        <textarea name="address" id="address" class="form-control"></textarea>
                    </div>
                    <div class="form-group col-md-12 pull-left">
                        <label for="description">Description</label>
                        <textarea name="description" id="description" class="form-control"></textarea>
                    </div>
			    </div>
                <div class="modal-footer" id="modal-footer">
                    <button type="submit" class="btn btn-primary">SAVE CHANGES</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">CLOSE</button>
                </div>
		    </div>
        </div>
    </div>
</form>

resources/views/employees/modals/employee-assets.blade.php
<form action="{{ route('employees.store.assets', [$employee->employee_id]) }}" method="post">
    @csrf
    <div class="modal fade" id="employee-assets" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="title" id="smallModalLabel">Employee Assets</h4>
                </div>
                <div class="modal-body">
                    <div class="form-group col-4 pull-left">
                        <label for="asset_type_id">Asset Type</label>
                        <select name="asset_type_id" id="asset_type_id" class="simple-select2 w-100">
                            <option value="">Asset Type</option>
                            @foreach($asset_types as $asset_type)
                            <option value="{{ $asset_type->id }}">{{ $asset_type->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-4 pull-left">
                        <label for="asset_brand_id">Brand</label>
                        <select name="asset_brand_id" id="asset_brand_id" class="simple-select2 w-100">
                            <option value="">Brand</option>
                            @foreach($asset_brands as $asset_brand)
                            <option value="{{ $asset_brand->id }}">{{ $asset_brand->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-4 pull-left">
                        <label for="asset_condition_id">Condition</label>
                        <select name="asset_condition_id" id="asset_condition_id" class="simple-select2 w-100">
                            <option value="">Condition</option>
                            @foreach($asset_conditions as $asset_condition)
                            <option value="{{ $asset_condition->id }}">{{ $asset_condition->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-12 pull-left">
                        <label for="serial_no">Serial No.</label>
                        <input type="text" name="serial_no" id="serial_no" class="form-control" placeholder="Serial No.">
                    </div>
                    <div class="form-group col-4 pull-left">
                        <label for="currency_id">Currency</label>
                        <select name="currency_id" id="currency_id" class="simple-select2 w-100">
                            <option value="">Currency</option>
                            @foreach($currencies as $currency)
                            <option value="{{ $currency->id }}">{{ $currency->symbol }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-8 pull-left">
                        <label for="value">Value</label>
                        <input type="text" name="value" id="value" class="form-control" placeholder="Value">
                    </div>
                    <div class="form-group col-12 pull-left">
                        <label for="description">Description</label>
                        <textarea class="form-control" name="description" id="description"></textarea>
                    </div>
                    <div class="form-group col-6 pull-left"">
                        <label for="issue_date">Issue Date</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="icon-calendar"></i></span>
                            </div>
                            <input name="issue_date" id="issue_date" data-provide="datepicker" data-date-autoclose="true" class="form-control" data-date-format="yyyy-mm-dd" placeholder="Issue Date">
                        </div>
                    </div>
                    <div class="form-group col-6 pull-left"">
                        <label for="return_date">Return Date</label>
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="icon-calendar"></i></span>
                            </div>
                            <input name="return_date" id="return_date" data-provide="datepicker" data-date-autoclose="true" class="form-control" data-date-format="yyyy-mm-dd" placeholder="Return Date">
                        </div>
                    </div>
                </div>
                <div class="modal-footer" id="modal-footer">
                    <button type="submit" class="btn btn-primary">SAVE CHANGES</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">CLOSE</button>
                </div>
            </div>
        </div>
    </div>
</form>

resources/views/employees/modals/employee-bank-account.blade.php
<form action="{{ route('employees.store.accountDetails', [$employee->employee_id]) }}" method="POST">
    @csrf
	<div class="modal fade" id="employee-bank-account" tabindex="-1" role="dialog">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="title" id="defaultModalLabel">Employee Bank Information</h4>
				</div>
				<div class="modal-body">
					<div class="form-group col-12 pull-left">
						<label for="bank_id">Bank Name</label>
						<select name="bank_id" class="simple-select2 w-100">
							<option value="">Bank Name</option>
                            @foreach($banks as $bank)
                                <option value="{{ $bank->id }}">{{ $bank->name }}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group col-12 pull-left">
                        <label for="account_no">Account Number</label>									
                        <input type="text" class="form-control" name="account_no" id="account_no" placeholder="Account Number">
                    </div>
                    <div class="form-group col-12 pull-left">
                        <label for="iban_no">IBAN Number (23 Digits)</label>									
                        <input type="text" class="form-control" name="iban_no" id="iban_no" placeholder="IBAN Number">
                    </div>
                    <div class="form-group col-12 pull-left">
                        <label for="account_holdar_name">Account Holdar Name</label>
                        <input type="text" class="form-control" name="account_holdar_name" id="account_holdar_name" placeholder="Account Holdar Name">
                    </div>
                    <div class="form-group col-md-12 pull-left">
                        <label for="description">Description</label>
                        <textarea name="description" id="description" class="form-control"></textarea>
                    </div>
                </div>
                <div class="modal-footer" id="modal-footer">
                    <button type="submit" class="btn btn-primary">SAVE CHANGES</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">CLOSE</button>
                </div>
            </div>
        </div>
    </div>
</form>