routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\EmployeeDependantController;
use App\Http\Controllers\ContactPersonController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
require __DIR__.'/auth.php';

Route::middleware(['auth'])->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/test', [UserController::class, 'test'])->name('test');
    
    Route::resource('/dependants', EmployeeDependantController::class);
    Route::resource('/contactPerson', ContactPersonController::class);
    
    
    Route::resource('/employees', EmployeeController::class);
    Route::group(['prefix' => 'employees','as' => 'employees.'],function(){
        Route::post('/{id}/contact-person', [EmployeeController::class, 'storeContactPerson'])->name('store.contactPerson');
        Route::post('/{id}/dependants', [EmployeeController::class, 'storeDependants'])->name('store.dependants');
        Route::post('/{id}/education', [EmployeeController::class, 'storeEducation'])->name('store.educationDetail');
        Route::post('/{id}/bank-details', [EmployeeController::class, 'storeAccountDetails'])->name('store.accountDetails');
        Route::post('/{id}/documents', [EmployeeController::class, 'storeDocuments'])->name('store.documents');
        Route::post('/{id}/assets', [EmployeeController::class, 'storeAssets'])->name('store.assets');
        Route::post('/{id}/dependant-benefits', [EmployeeController::class, 'storeDependantBenefits'])->name('store.dependantBenefits');
        Route::put('/{id}/main-info', [EmployeeController::class, 'updateEmployeeMainInfo'])->name('update.mainInfo');
        Route::put('/{id}/personal-details', [EmployeeController::class, 'updateEmployeePersonalDetails'])->name('update.personalDetails');
        Route::put('/{id}/employee-contact', [EmployeeController::class, 'updateEmployeeContactDetails'])->name('update.contactDetails');
        Route::put('/{id}/employee-official-details', [EmployeeController::class, 'updateEmployeeOfficialDetails'])->name('update.officialDetails');
        Route::put('/{id}/employee-profile-image', [EmployeeController::class, 'updateProfileImage'])->name('update.profileImage');
        Route::put('/{id}/employee-rules', [EmployeeController::class, 'updateEmployeeRules'])->name('update.employeeRules');
    });
});

app/Models/EmployeeType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class EmployeeType extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'name',
        'description',
        'status',
        'created_by',
        'updated_by',
    ];

    public function employees(){
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\EmployeeType;
use App\Models\VisaStatus;
use App\Models\EmployeeCategory;
use App\Models\Company;
use App\Models\Sponsor;
use App\Models\PayGroup;
use App\Models\Country;
use App\Models\City;
use App\Models\Relation;
use App\Models\Religion;
use App\Models\EmployeeDependant;
use App\Models\Qualification;
use App\Models\Institute;
use App\Models\Bank;
use App\Models\DocumentType;
use App\Models\DocumentStatus;
use App\Models\AssetType;
use App\Models\AssetCondition;
use App\Models\AssetBrand;
use App\Models\Currency;
use App\Models\InsuranceCategory;
use App\Models\InsuranceCompany;
use App\Models\Route;
use App\Models\PositionCategory;
use App\Models\Designation;
use App\Models\Department;
use App\Models\SubDepartment;
use App\Models\CostCenter;
use App\Models\Project;
use App\Models\TicketEntitlement;
use App\Models\EmployeeStatus;
use App\Models\ContractType;
use App\Models\Shift;
use App\Models\LeavePerAnnum;
use App\Http\Requests\EditUserProfile;
use Illuminate\Http\Request;
use Illuminate\Http\Exceptions\HttpResponseException;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Intervention\Image\Facades\Image as Image;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = User::get()->all();
        return view('employees.list', ['employees' => $employees]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $employee = User::create([
            'employee_id' => 'EMP_ID_004',
            'personal_id' => $request->personal_id,
            'emirates_id' => $request->emirates_id,
            'first_name' => $request->first_name,
            'middle_name' => $request->middle_name,
            'last_name' => $request->last_name,
            'full_name' => $request->first_name . ' ' . $request->middle_name . ' ' . $request->last_name,
            'email' => $request->email,
            'password' => Hash::make('password'),
            'home_phone_number' => $request->home_phone_number,
            'profile_image' => 'default_image.jpg',
        ]);
        return redirect()->route('employees.index')->with('status', 'Employee Created Successfuly!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(user $employee)
    {
        // return [$employee->dependants];
        $employee = User::with([
            'employeeType',
            'visaStatus',
            'employeeCategory',
            'contactPeoples.relationName',
            'linemanager',
            'dependants.relation',
            'educations.country',
            'educations.qualification',
            'employeeBankDetail'
        ])->find($employee->employee_id);
        $contactPersons = $employee->contactPeoples;
        $educations = $employee->educations;
        $employeeDependants = $employee->dependants;
        $employeeEducations = $employee->education;
        $employeeDocuments = $employee->documents;
        $employeeDependantsBenefits = $employee->dependantBenefits;
        $employeeAssets = $employee->assets;
        $bankDetails = $employee->bankDetails;
        $employee_types = EmployeeType::select(['id', 'name'])->get();
        $employee_categories = EmployeeCategory::select(['id', 'name'])->get();
        $visa_statuses = VisaStatus::select(['id', 'name'])->get();
        $line_managers = User::select(['employee_id', 'full_name'])->get();
        $companies = Company::select(['id', 'name'])->get();
        $sponsors = Sponsor::select(['id', 'name'])->get();
        $pay_groups = PayGroup::select(['id', 'name'])->get();
        $nationalities = Country::select(['id', 'name'])->get();
        $relations = Relation::select(['id', 'name'])->get();
        $religions = Religion::select(['id', 'name'])->get();
        $document_statuses = DocumentStatus::select(['id', 'name'])->get();
        $document_types = DocumentType::select(['id', 'name'])->get();
        $asset_types = AssetType::select(['id', 'name'])->get();
        $asset_conditions = AssetCondition::select(['id', 'name'])->get();
        $asset_brands = AssetBrand::select(['id', 'name'])->get();
        $banks = Bank::select(['id', 'name'])->get();
        $qualifications = Qualification::select(['id', 'name'])->get();
        $institutes = Institute::select(['id', 'name'])->get();
        $currencies = Currency::select(['id', 'name', 'symbol'])->get();
        $employee_dependent_names = EmployeeDependant::select(['id', 'name'])->where('user_employee_id', $employee->employee_id)->get();
        $insurance_companies = InsuranceCompany::select(['id', 'name'])->get();
        $insurance_categories = InsuranceCategory::select(['id', 'name'])->get();
        $ticket_entitlements = TicketEntitlement::select(['id', 'name'])->get();
        $routes = Route::select(['id', 'name'])->get();
        $positionCategories = PositionCategory::select(['id', 'name'])->get();
        $designations = Designation::select(['id', 'name'])->get();
        $departments = Department::select(['id', 'name'])->get();
        $subDepartments = SubDepartment::select(['id', 'name'])->get();
        $cities = City::select(['id', 'name', 'country_id'])->get();
        $costCenters = CostCenter::select(['id', 'name'])->get();
        $projects = Project::select(['id', 'name'])->get();
        $employeeStatuses = EmployeeStatus::select(['id', 'name'])->get();
        $contractTypes = ContractType::select(['id', 'name'])->get();
        $shifts = Shift::select(['id', 'name'])->get();
        $leaveRules = LeavePerAnnum::select(['id', 'name'])->get();
        $maritialStatus = config('basic.maritial_status');
        $bloodGroup = config('basic.blood_group');
        $employeeGender = config('basic.employee_gender');
        $probationPeriod = config('basic.probation_period');

        return view('employees.profile', [
            'contractTypes'             => $contractTypes,
            'shifts'                    => $shifts,
            'leaveRules'                => $leaveRules,
            'countries'                 => $nationalities,
            'employee'                  => $employee,
            'employee_types'            => $employee_types,
            'visa_statuses'             => $visa_statuses,
            'employee_categories'       => $employee_categories,
            'line_managers'             => $line_managers,
            'companies'                 => $companies,
            'sponsors'                  => $sponsors,
            'pay_groups'                => $pay_groups,
            'nationalities'             => $nationalities,
            'relations'                 => $relations,
            'religions'                 => $religions,
            'employeeDependants'        => $employeeDependants,
            'qualifications'            => $qualifications,
            'institutes'                => $institutes,
            'contactPersons'            => $contactPersons,
            'educations'                => $educations,
            'bankDetails'               => $bankDetails,
            'banks'                     => $banks,
            'document_statuses'         => $document_statuses,
            'document_types'            => $document_types,
            'employeeDocuments'         => $employeeDocuments,
            'asset_types'               => $asset_types,
            'asset_conditions'          => $asset_conditions,
            'asset_brands'              => $asset_brands,
            'currencies'                => $currencies,
            'employeeAssets'            => $employeeAssets,
            'employee_dependent_names'  => $employee_dependent_names,
            'insurance_companies'       => $insurance_companies,
            'insurance_categories'      => $insurance_categories,
            'ticket_entitlements'       => $ticket_entitlements,
            'routes'                    => $routes,
            'employeeDependantsBenefits' => $employeeDependantsBenefits,
            'maritialStatus'            => $maritialStatus,
            'bloodGroup'                => $bloodGroup,
            'employeeGender'            => $employeeGender,
            'probationPeriod'           => $probationPeriod,
            'positionCategories'        => $positionCategories,
            'designations'              => $designations,
            'departments'               => $departments,
            'subDepartments'            => $subDepartments,
            'cities'                    => $cities,
            'costCenters'               => $costCenters,
            'projects'                  => $projects,
            'employeeStatuses'          => $employeeStatuses
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(user $employee)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EditUserProfile $request, user $employee)
    {
        try {
            $full_name = $request->first_name . ' ' . $request->middle_name . ' ' . $request->last_name;

resources/views/employees/list.blade.php
@extends('layouts.templates')
@section('content')

    <div id="main-content">
        <div class="container-fluid">
            <div class="block-header">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12">
                        <h2><a href="javascript:void(0);" class="btn btn-xs btn-link btn-toggle-fullwidth"><i lass="fa fa-arrow-left"></i></a> Employee List</h2>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}"><i class="icon-home"></i></a></li>
                            <li class="breadcrumb-item">Employee</li>
                            <li class="breadcrumb-item active">Employee List</li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="row clearfix">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="header">
                            <h2>Employee List</h2>
                            <ul class="header-dropdown">
                                <li><button class="btn btn-primary ml-auto" data-toggle="modal" data-target="#add-employee">Add Employee</button></li>
                            </ul>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-hover js-basic-example dataTable table-custom table-striped m-b-0 c_list">
                                    <thead class="thead-dark">
                                        <tr>
                                            <th></th>
                                            <th>Name</th>
                                            <th>Employee ID</th>
                                            <th>Phone</th>
                                            <th>Join Date</th>
                                            <th>Department</th>
                                            <th>Designation</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($employees as $employee)
                                            <tr>
                                                <td class="width45">
                                                    @php
                                                        $path = Storage::disk('media_images')->exists($employee->employee_id . '/profile.jpg') ? asset('media_images/' . $employee->employee_id . '/profile.jpg') : asset('media_images/profile.jpg');
                                                    @endphp
                                                    <img src="{{$path}}" class="rounded-circle avatar" alt=""/>
                                                </td>
                                                <td>
                                                    <h6 class="mb-0">{{ $employee->full_name }}</h6>
                                                    <span>{{ $employee->email }}</span>
                                                </td>
                                                <td><span>{{ $employee->employee_id }}</span></td>
                                                <td><span>{{ $employee->home_phone_number ?? 'N/A' }}</span></td>
                                                <td>{{ $employee->date_of_joining ?? 'N/A' }}</td>
                                                <td>{{ $employee->department->name ?? 'N/A' }}</td>
                                                <td>{{ $employee->designation->name ?? 'N/A' }}</td>
                                                <td>
                                                    <form action="{{ route('employees.destroy', [$employee]) }}"
                                                        method="POST">
                                                        @method('DELETE')
                                                        <a href="{{ route('employees.show', [$employee]) }}"><button
                                                                type="button" class="btn btn-sm btn-outline-secondary"
                                                                title="Edit"><i class="fa fa-eye"></i></button></a>
                                                        <button type="button"
                                                            class="btn btn-sm btn-outline-danger js-sweetalert"
                                                            title="Delete" data-type="confirm"
                                                            data-value="{{ $employee->employee_id }}"
                                                            data-model="employees"
                                                            value="{{ $employee->employee_id }}"><i
                                                                class="fa fa-trash-o"></i></button>
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Default Size -->
    @include('employees.modals.add-employee')

@endsection